### ISSUE TITLE
Cambiar CNAME

### ISSUE THREAD

**Issue by paulomcnally** [nodenica/nodenica-website#14]
- [x] Duplicar entorno en Heroku [nuevo](http://nodenica-website.herokuapp.com/)
- [x] Cambiar CNAME del dominio nodenica.com

El dyno actual se está deteniendo con frecuencia, supongo que es un dyno viejo en heroku.

**Comment by amosrivera** [comment]
#offtopic sweet! no sabía que podías poner checkboxes así.

**Comment by paulomcnally** [comment]
https://help.github.com/articles/writing-on-github/
